# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
    args: ["--maxkb=2000"]
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    exclude: ^conda\.recipe/meta\.yaml$
  - id: debug-statements
#  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.5
  hooks:
    # Run the linter.
    - id: ruff
    #    args: [ --fix ]
    # Run the formatter.
    # - id: ruff-format

## Black, the code formatter, natively supports pre-commit
#- repo: https://github.com/psf/black
#  rev: 22.3.0
#  hooks:
#  - id: black
#    exclude: ^(docs)

## Sort your imports in a standard form
#- repo: https://github.com/PyCQA/isort
#  rev: 5.10.1
#  hooks:
#  - id: isort

# Upgrade older Python syntax
#- repo: https://github.com/asottile/pyupgrade
#  rev: v2.31.1
#  hooks:
#  - id: pyupgrade
#    args: ["--py36-plus"]

## Changes tabs to spaces
#- repo: https://github.com/Lucas-C/pre-commit-hooks
#  rev: v1.1.13
#  hooks:
#  - id: remove-tabs
#    exclude: ^(docs)

## CMake formatting
#- repo: https://github.com/cheshirekow/cmake-format-precommit
#  rev: v0.6.13
#  hooks:
#  - id: cmake-format
#    additional_dependencies: [pyyaml]
#    types: [file]
#    files: (\.cmake|CMakeLists.txt)(.in)?$

# Suggested hook if you add a .clang-format file
# - repo: https://github.com/pre-commit/mirrors-clang-format
#  rev: v13.0.0
#  hooks:
#  - id: clang-format
