name: "Pip"

on:
  workflow_dispatch:
  pull_request:
  push:

env:
  MACOSX_DEPLOYMENT_TARGET: "11.0"
  DISPLAY: ":0"

jobs:
  build:
    name: Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: install xorg-dev & start Xvfb (ubuntu only)
      if: ${{ matrix.platform == 'ubuntu-latest' }}
      run: |
        sudo apt-get update && sudo apt-get install -y xorg-dev
        sudo apt-get install -y xvfb
        Xvfb :99 &
        echo "DISPLAY=:99.0" >> $GITHUB_ENV

    - name: install mesa OpenGL software renderer (windows only)
      shell: bash
      if: ${{ matrix.platform == 'windows-latest' }}
      run: |
        # Download the archive
        curl -L -O https://github.com/pal1000/mesa-dist-win/releases/download/23.1.9/mesa3d-23.1.9-release-msvc.7z

        # Extract the archive using 7-zip which is preinstalled on the GitHub Actions Windows runner
        7z x mesa3d-23.1.9-release-msvc.7z -omesa3d

        # copy the mesa DLLs to the python directory
        python_dir=$(dirname $(which python))
        cp mesa3d/x64/*.* $python_dir

#    - name: Setup interactive tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: Build and install
      shell: bash
      run: |
        # optionally: export IMMVISION_FETCH_OPENCV=OFF
        pip install --verbose .[test]

    - name: pytest
      run: pytest

    - name: CI Automation python test (ubuntu)
      shell: bash
      if: ${{ matrix.platform == 'ubuntu-latest' }}
      run: |
        cd .github/ci_automation_tests
        python ci_automation_test_app_bundle.py
