name: "CppLib"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main
      - dev

env:
  MACOSX_DEPLOYMENT_TARGET: "11.0"

jobs:
  build:
    name: Cpp Lib
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-2019, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    #- name: Setup interactive tmate session
    #  if: ${{ matrix.platform == 'ubuntu-latest' }}
    #  uses: mxschmitt/action-tmate@v3

    - name: install xorg-dev on ubuntu
      run: ./ci_scripts/install_xorg_dev.sh

    # Install OpenCV (ubuntu & macos)
    #- name: install OpenCV (ubuntu)
    #  if: ${{ matrix.platform == 'ubuntu-latest' }}
    #  run: sudo apt-get install -y libopencv-dev
    #- name: install OpenCV (macos)
    #  if: ${{ matrix.platform == 'macos-latest' }}
    #  run: brew install opencv

    # Install conan & pybind11
    - name: install conan and pybind11 (linux and ubuntu)
      if: ${{ matrix.platform != 'windows-2019' }}
      run:  ./ci_scripts/install_conan_pybind11.sh
    - name: install conan and pybind11 (windows)
      if: ${{ matrix.platform == 'windows-2019' }}
      run: |
        python3 -m pip install conan
        conan profile new default --detect
        python3 -m pip install pybind11

    - name: Build and install
      shell: bash
      run: |
        # Optional: set IMMVISION_FETCH_OPENCV to OFF to disable OpenCV/Immvision
        # ------------------------------------------------------------------------------------
        # export IMMVISION_FETCH_OPENCV=OFF
        #
        # cmake and build
        # ------------------------------------------------------------------------------------
        mkdir build
        cd build
        cmake .. -DIMGUI_BUNDLE_BUILD_PYTHON=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release -j 3
