name: "Metal"

# Test that Metal build works on Apple
on:
  workflow_dispatch:
  pull_request:
  push:


jobs:
  build:
    name: Metal
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install glfw2 and sdl2
        shell: bash
        run: |
          brew install glfw sdl2

      - name: Build and install
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DHELLOIMGUI_USE_GLFW_METAL=ON -DHELLOIMGUI_USE_SDL_METAL=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build . -j 3
