name: "Pip"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main
      - dev

env:
  MACOSX_DEPLOYMENT_TARGET: "11.0"
  DISPLAY: ":0"

jobs:
  build:
    name: Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-2019, macos-latest, ubuntu-latest]
        # "pypy-3.9" was removed from python-version because numpy install fails
        python-version: ["3.7", "3.10"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: install xorg-dev on ubuntu
      if: ${{ matrix.platform == 'ubuntu-latest' }}
      run: ./ci_scripts/install_xorg_dev.sh

    # Install OpenCV (ubuntu & macos)
    #- name: install OpenCV (ubuntu)
    #  if: ${{ matrix.platform == 'ubuntu-latest' }}
    #  run: sudo apt-get install -y libopencv-dev
    #- name: install OpenCV (macos)
    #  if: ${{ matrix.platform == 'macos-latest' }}
    #  run: brew install opencv

    #    - name: Setup interactive tmate session
    #      uses: mxschmitt/action-tmate@v3

    - name: Build and install
      shell: bash
      run: |
        # Optional: set IMMVISION_FETCH_OPENCV to OFF to disable OpenCV/Immvision
        # ------------------------------------------------------------------------------------
        # export IMMVISION_FETCH_OPENCV=OFF

        #
        # Build pip
        # ------------------------------------------------------------------------------------
        pip install --verbose .[test]

    - name: Test
      run: pytest
